services:
  oracle_db:
   image: oracle/database:23.5.0-free
   container_name: oracle_test_db
   shm_size: 1g # 共有メモリを1GB以上にしないとコンテナ起動時にエラーが発生します。
   environment:
     - TZ=Asia/Tokyo
     - LANGUAGE=ja_JP.ja
     - LANG=ja_JP.UTF-8
     - NLS_LANG=Japanese_Japan.AL32UTF8 # sqlplusの日本語化でこの環境変数が必要になります。
     - ORACLE_PWD=pass # パスワードは適宜指定します。
   ports:
     - 11521:1521
   volumes:
     - ./src:/opt/oracle/oradata